# Generated by Django 5.2.8 on 2026-04-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_user_bio_user_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.CharField(blank=True, help_text='Apni skills likhein (e.g., Python, Django, React)', max_length=255, null=True),
        ),
    ]
