# Generated by Django 5.2.8 on 2026-03-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='auto_apply_enabled',
            field=models.BooleanField(default=False, help_text='AI ko ijazat dein ke wo aapke liye apply kare'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='auth_user',
        ),
    ]
